services:
  supply-chain-scenario-rag-db:
    image: docker.io/postgres:16
    labels:
      com.quickstart.package: db
    environment:
      POSTGRES_DB: supply-chain-scenario-rag
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - supply-chain-scenario-rag_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d supply-chain-scenario-rag"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  supply-chain-scenario-rag_postgres_data:
