{{- if and .Values.backend.enabled .Values.backend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-backend
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.backend.route.timeout | quote }}
spec:
  {{- if .Values.backend.route.host }}
  host: {{ .Values.backend.route.host | quote }}
  {{- end }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Release.Name }}-backend
  port:
    targetPort: http
{{- end }}
