{{- if .Values.frontend.enabled }}
{{- $backendUpstream := .Values.frontend.apiProxyUpstream }}
{{- if not $backendUpstream }}
{{- $backendUpstream = printf "http://%s-backend:%v" .Release.Name .Values.backend.service.port }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: BACKEND_UPSTREAM
              value: {{ $backendUpstream | quote }}
            - name: API_PROXY_CONNECT_TIMEOUT
              value: {{ .Values.frontend.apiProxy.connectTimeout | quote }}
            - name: API_PROXY_SEND_TIMEOUT
              value: {{ .Values.frontend.apiProxy.sendTimeout | quote }}
            - name: API_PROXY_READ_TIMEOUT
              value: {{ .Values.frontend.apiProxy.readTimeout | quote }}
{{- end }}
